version: "2"
services:
  app:
    container_name: sfb-api
    build:
      context: ../
      dockerfile: deployments/sfb/Dockerfile
    volumes:
      - type: bind
        source: ${MNT_LOC}
        target: ${MNT_LOC}
    ports:
      - "5000:5000"